FROM node:20-alpine AS base

FROM base AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
COPY turbo.json ./
COPY apps ./apps
COPY packages ./packages
COPY sanity ./sanity
RUN npm install
RUN npx turbo run build --filter=web

FROM base AS runner
WORKDIR /app
ENV NODE_ENV production
ENV PORT 8080

COPY --from=builder /app/apps/web/public ./apps/web/public
COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static

EXPOSE 8080
CMD ["node", "apps/web/server.js"]
